#!/bin/bash

HUB_REPO=raidennetwork/scenario-player

build_image () {
    raiden_version=$1
    scenario_version=$2
    docker build \
        --build-arg RAIDEN_VERSION=${raiden_version} \
        --build-arg SP_VERSION=${SP_VERSION} \
        --build-arg SCENARIOS_VERSION=${scenario_version} \
        --tag ${HUB_REPO}:sp-${SP_VERSION}-raiden-${raiden_version}-scenarios-${scenario_version}\
        .
}
push_image () {
    raiden_version=$1
    scenario_version=$2
    docker push ${HUB_REPO}:sp-${SP_VERSION}-raiden-${raiden_version}-scenarios-${scenario_version}
}

if [[ "${DOCKER_TAG}" == "latest" ]]; then
    # Don't build additional tags on `latest`
    exit 0
else
    SP_VERSION=${DOCKER_TAG}
    for raiden_version in master develop; do
        for scenario_version in master develop; do
            build_image ${raiden_version} ${scenario_version};
            push_image ${raiden_version} ${scenario_version};
        done
    done
fi