from scenario_player.services.releases.blueprints.archives import archives_views
from scenario_player.services.releases.blueprints.binaries import binaries_views
from scenario_player.services.releases.blueprints.releases import releases_views
